### ISSUE TITLE
would it be possible to get the request id out of log context?

### ISSUE THREAD

**Issue by jappeace** [Disco-Dave/katip-wai#1]
This will allow me to use it as trace id for other functions that aren't used by requests as well (eg background jobs).

**Comment by Disco-Dave** [comment]
Hey @jappeace thanks for making this issue.

I don't think the current api allows for this, but this is something that I've been wanting as well. I'll try to find time this weekend or next week to see if I can come up with a solution.

**Comment by Disco-Dave** [comment]
Hey, this is now possible with version 0.2.0.0.

You can see the example here:
1. Add the active request to the `AppM` in the project: https://github.com/Disco-Dave/katip-wai/blob/060fd48df5e1492a864172891592d76119685a14/example/src/Katip/Wai/Example/Middleware.hs#L36
2. And then you can retrieve the active request with its trace id here: https://github.com/Disco-Dave/katip-wai/blob/060fd48df5e1492a864172891592d76119685a14/example/src/Katip/Wai/Example/Servant.hs#L49

Let me know if you any questions or concerns.

**Comment by jappeace** [comment]
thank you!
